[2024-04-07T21:38:35.917-0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.extract scheduled__2024-04-07T00:00:00+00:00 [queued]>
[2024-04-07T21:38:35.919-0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.extract scheduled__2024-04-07T00:00:00+00:00 [queued]>
[2024-04-07T21:38:35.919-0500] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-07T21:38:35.923-0500] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract> on 2024-04-07 00:00:00+00:00
[2024-04-07T21:38:35.926-0500] {standard_task_runner.py:60} INFO - Started process 65435 to run task
[2024-04-07T21:38:35.929-0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'extract', 'scheduled__2024-04-07T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/basic_etl.py', '--cfg-path', '/var/folders/qt/4kz3_8fn6hx612tyl9tj4dbm0000gn/T/tmp2mk1wtep']
[2024-04-07T21:38:35.930-0500] {standard_task_runner.py:88} INFO - Job 3: Subtask extract
[2024-04-07T21:38:35.944-0500] {task_command.py:423} INFO - Running <TaskInstance: etl_dag.extract scheduled__2024-04-07T00:00:00+00:00 [running]> on host jamess-air-4.attlocal.net
[2024-04-07T21:38:35.963-0500] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-07T00:00:00+00:00'
[2024-04-07T21:38:35.966-0500] {python.py:202} INFO - Done. Returned value was:    id        date  amount
0   1  2024-04-01    30.0
1   2  2024-04-02    60.0
2   3  2024-04-03   180.0
[2024-04-07T21:38:35.970-0500] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 451, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/Users/james/Desktop/projects/airflow-local/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/james/Desktop/projects/airflow-local/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3013, in xcom_push
    XCom.set(
  File "/Users/james/Desktop/projects/airflow-local/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/james/Desktop/projects/airflow-local/venv/lib/python3.9/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/Users/james/Desktop/projects/airflow-local/venv/lib/python3.9/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/james/Desktop/projects/airflow-local/venv/lib/python3.9/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/james/Desktop/projects/airflow-local/venv/lib/python3.9/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/Users/james/Desktop/projects/airflow-local/venv/lib/python3.9/site-packages/airflow/serialization/serde.py", line 148, in serialize
    data, serialized_classname, version, is_serialized = _serializers[qn].serialize(o)
  File "/Users/james/Desktop/projects/airflow-local/venv/lib/python3.9/site-packages/airflow/serialization/serializers/pandas.py", line 40, in serialize
    import pyarrow as pa
ModuleNotFoundError: No module named 'pyarrow'
[2024-04-07T21:38:35.980-0500] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=extract, execution_date=20240407T000000, start_date=20240408T023835, end_date=20240408T023835
[2024-04-07T21:38:35.983-0500] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task extract (No module named 'pyarrow'; 65435)
[2024-04-07T21:38:35.990-0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-07T21:38:35.997-0500] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
